# Generated by Django 6.0 on 2026-01-11 15:13

import apppolizas.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('contacto', models.CharField(max_length=100)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('id_broker', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableCustodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista de Seguros'), ('gerente', 'Gerencia'), ('solicitante', 'Solicitante')], default='analista', max_length=20)),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipo_alerta', models.CharField(choices=[('VENCIMIENTO_POLIZA', 'Vencimiento de Póliza'), ('PAGO_PENDIENTE', 'Pago por Realizar'), ('SINIESTRO_DEMORA_DOC', 'Retraso Documentación Siniestro'), ('SINIESTRO_RESPUESTA_ASEG', 'Retraso Respuesta Aseguradora'), ('OTRO', 'Otro')], max_length=50)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Lectura'), ('LEIDA', 'Leída'), ('ENVIADA_CORREO', 'Enviada por Correo')], default='PENDIENTE', max_length=50)),
                ('enviado_por_correo', models.BooleanField(default=False)),
                ('id_referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=50, unique=True)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fin', models.DateField()),
                ('monto_asegurado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ramo', models.CharField(max_length=100)),
                ('objeto_asegurado', models.CharField(max_length=100)),
                ('prima_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prima_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.BooleanField(default=True)),
                ('renovable', models.BooleanField(default=False)),
                ('fecha_emision', models.DateField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='apppolizas.aseguradora')),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='apppolizas.broker')),
                ('usuario_gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('documento_contable', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('prima', models.DecimalField(decimal_places=2, help_text='Valor de la prima', max_digits=12)),
                ('contribucion_super', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seguro_campesino', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('derechos_emision', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retenciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_pronto_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mensaje_resultado', models.CharField(blank=True, max_length=255, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='apppolizas.poliza')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoPoliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='polizas/')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='apppolizas.poliza')),
            ],
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reclamo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha_siniestro', models.DateField()),
                ('fecha_notificacion', models.DateField(auto_now_add=True)),
                ('tipo_siniestro', models.CharField(max_length=100)),
                ('ubicacion_bien', models.CharField(max_length=255)),
                ('causa_siniestro', models.TextField()),
                ('nombre_bien', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_activo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_tramite', models.CharField(choices=[('REPORTADO', 'Reportado'), ('DOCUMENTACION', 'En validación'), ('ENVIADO_ASEGURADORA', 'Enviado a Aseguradora'), ('LIQUIDADO', 'Liquidado'), ('RECHAZADO', 'Rechazado')], default='REPORTADO', max_length=50)),
                ('cobertura_aplicada', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_reclamo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custodio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siniestros', to='apppolizas.responsablecustodio', verbose_name='Responsable o Custodio')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='apppolizas.poliza')),
                ('usuario_gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Finiquito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_finiquito', models.DateField()),
                ('id_finiquito', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_total_reclamo', models.DecimalField(decimal_places=2, help_text='Monto bruto reclamado', max_digits=12)),
                ('valor_deducible', models.DecimalField(decimal_places=2, help_text='Deducible aplicado', max_digits=12)),
                ('valor_depreciacion', models.DecimalField(decimal_places=2, default=0, help_text='Depreciación del bien', max_digits=12)),
                ('valor_final_pago', models.DecimalField(decimal_places=2, help_text='Valor líquido a recibir', max_digits=12)),
                ('documento_firmado', models.FileField(blank=True, null=True, upload_to='finiquitos/')),
                ('fecha_pago_realizado', models.DateField(blank=True, null=True)),
                ('pagado_a_usuario', models.BooleanField(default=False)),
                ('siniestro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finiquito', to='apppolizas.siniestro')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSiniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apppolizas.models.ruta_documento_siniestro)),
                ('tipo', models.CharField(choices=[('INFORME', 'Informe Técnico'), ('DENUNCIA', 'Denuncia'), ('FOTOS', 'Fotografías'), ('FACTURA_REPARACION', 'Facturas Reparación'), ('OTRO', 'Otros')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('siniestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='apppolizas.siniestro')),
            ],
        ),
    ]
