# Generated by Django 6.0 on 2025-12-28 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppolizas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista')], default='analista', max_length=20),
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reclamo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha_siniestro', models.DateField()),
                ('tipo_siniestro', models.CharField(max_length=100)),
                ('ubicacion_bien', models.CharField(max_length=255)),
                ('causa_siniestro', models.TextField()),
                ('nombre_bien', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_activo', models.CharField(blank=True, max_length=50, null=True)),
                ('responsable_custodio', models.CharField(max_length=150)),
                ('estado_tramite', models.CharField(choices=[('REPORTADO', 'Reportado'), ('DOCUMENTACION', 'En validación de documentos'), ('ENVIADO_ASEGURADORA', 'Enviado a Aseguradora'), ('LIQUIDADO', 'Liquidado'), ('RECHAZADO', 'Rechazado')], default='REPORTADO', max_length=50)),
                ('fecha_notificacion', models.DateField(auto_now_add=True)),
                ('cobertura_aplicada', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_reclamo', models.FloatField(default=0.0)),
                ('deducible_aplicado', models.FloatField(default=0.0)),
                ('depreciacion', models.FloatField(default=0.0)),
                ('valor_a_pagar', models.FloatField(default=0.0)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='apppolizas.poliza')),
                ('usuario_gestor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestros_gestionados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
